import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import Navbar from '../components/navbar/Navbar';

// import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center">
        {/* <Navbar /> */}
        <div className="pt-[20%]">
          <h1 className="ml-[25px] ">Home</h1>

          <div className="">
            <Link href={'/login'}>
              <button
                className="bg-sky-600 hover:bg-sky-700 border px-6 py-1 
              rounded-full text-white"
              >
                Login
              </button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
